name: Build and Release

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ "newGUI" ]
    tags:
      - "v*"   # triggers on version tags like v1.0.0

permissions:
  contents: write  # required to create releases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Ensure tag exists
        run: |
          if [[ "${GITHUB_REF}" != refs/tags/* ]]; then
            echo "This workflow must be run on a tag. use this command `git tag v1.0.0 && git push origin v1.0.0`"
            exit 1
          fi
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          make install
  
      - name: Build executable for camera calib app 
        run: |
          make compileCalib
      - name: Rename artifact
        run: |
          mkdir -p dist/cameraCalibGui && mv computer_code/api/dist/cameraCalibGui dist/cameraCalibGui

      - name: Upload artifact 
        uses: actions/upload-artifact@v4
        with:
          name: cameraCalibGui
          path: dist/cameraCalibGui

      - name: Build executable for camera calib app 
        run: |
          make compileTracking

      - name: Rename artifact
        run: |
          mkdir -p dist/viewapp && mv computer_code/api/dist/viewapp dist/viewapp

      - name: Upload artifact 
        uses: actions/upload-artifact@v4
        with:
          name: viewapp
          path: dist/viewapp

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/viewapp/viewapp
            dist/cameraCalibGui/cameraCalibGui
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
